image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master

.test-env:
  image: node:19.8.1-bullseye-slim
  stage: test
  before_script:
    - apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global --registry https://registry.npmmirror.com pnpm
    - pnpm config set registry https://registry.npmmirror.com
    - pnpm install

unit-test:
  extends: .test-env
  script:
    - pnpm coverage
  after_script:
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-mika-kawaii.tar.gz"
    - tar -xf "/tmp/sonar-mika-kawaii.tar.gz" -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

style-test:
  extends: .test-env
  script:
    - pnpm tsc --noEmit && pnpm lint

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
